//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegrador.ReferenciaNegocio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_USUARIO", Namespace="http://schemas.datacontract.org/2004/07/WcfServicio")]
    [System.SerializableAttribute()]
    public partial class TB_USUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APE_USUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_USUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMAIL_USUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_DISTRITOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_DOCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_TIPO_USUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOGIN_USUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOM_USUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_CONTACTO_USUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_DOC_USUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PASSWORD_USUField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APE_USU {
            get {
                return this.APE_USUField;
            }
            set {
                if ((object.ReferenceEquals(this.APE_USUField, value) != true)) {
                    this.APE_USUField = value;
                    this.RaisePropertyChanged("APE_USU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_USU {
            get {
                return this.COD_USUField;
            }
            set {
                if ((this.COD_USUField.Equals(value) != true)) {
                    this.COD_USUField = value;
                    this.RaisePropertyChanged("COD_USU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMAIL_USU {
            get {
                return this.EMAIL_USUField;
            }
            set {
                if ((object.ReferenceEquals(this.EMAIL_USUField, value) != true)) {
                    this.EMAIL_USUField = value;
                    this.RaisePropertyChanged("EMAIL_USU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_DISTRITO {
            get {
                return this.ID_DISTRITOField;
            }
            set {
                if ((this.ID_DISTRITOField.Equals(value) != true)) {
                    this.ID_DISTRITOField = value;
                    this.RaisePropertyChanged("ID_DISTRITO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_DOC {
            get {
                return this.ID_DOCField;
            }
            set {
                if ((this.ID_DOCField.Equals(value) != true)) {
                    this.ID_DOCField = value;
                    this.RaisePropertyChanged("ID_DOC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_ESTADO {
            get {
                return this.ID_ESTADOField;
            }
            set {
                if ((this.ID_ESTADOField.Equals(value) != true)) {
                    this.ID_ESTADOField = value;
                    this.RaisePropertyChanged("ID_ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_TIPO_USU {
            get {
                return this.ID_TIPO_USUField;
            }
            set {
                if ((this.ID_TIPO_USUField.Equals(value) != true)) {
                    this.ID_TIPO_USUField = value;
                    this.RaisePropertyChanged("ID_TIPO_USU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOGIN_USU {
            get {
                return this.LOGIN_USUField;
            }
            set {
                if ((object.ReferenceEquals(this.LOGIN_USUField, value) != true)) {
                    this.LOGIN_USUField = value;
                    this.RaisePropertyChanged("LOGIN_USU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOM_USU {
            get {
                return this.NOM_USUField;
            }
            set {
                if ((object.ReferenceEquals(this.NOM_USUField, value) != true)) {
                    this.NOM_USUField = value;
                    this.RaisePropertyChanged("NOM_USU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMERO_CONTACTO_USU {
            get {
                return this.NUMERO_CONTACTO_USUField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_CONTACTO_USUField, value) != true)) {
                    this.NUMERO_CONTACTO_USUField = value;
                    this.RaisePropertyChanged("NUMERO_CONTACTO_USU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUM_DOC_USU {
            get {
                return this.NUM_DOC_USUField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_DOC_USUField, value) != true)) {
                    this.NUM_DOC_USUField = value;
                    this.RaisePropertyChanged("NUM_DOC_USU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PASSWORD_USU {
            get {
                return this.PASSWORD_USUField;
            }
            set {
                if ((object.ReferenceEquals(this.PASSWORD_USUField, value) != true)) {
                    this.PASSWORD_USUField = value;
                    this.RaisePropertyChanged("PASSWORD_USU");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_TIPO_USUARIO", Namespace="http://schemas.datacontract.org/2004/07/WcfServicio")]
    [System.SerializableAttribute()]
    public partial class TB_TIPO_USUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_TIPO_USUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_TIPO_USUField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_TIPO_USU {
            get {
                return this.DES_TIPO_USUField;
            }
            set {
                if ((object.ReferenceEquals(this.DES_TIPO_USUField, value) != true)) {
                    this.DES_TIPO_USUField = value;
                    this.RaisePropertyChanged("DES_TIPO_USU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_TIPO_USU {
            get {
                return this.ID_TIPO_USUField;
            }
            set {
                if ((this.ID_TIPO_USUField.Equals(value) != true)) {
                    this.ID_TIPO_USUField = value;
                    this.RaisePropertyChanged("ID_TIPO_USU");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_TIPO_DOCUMENTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServicio")]
    [System.SerializableAttribute()]
    public partial class TB_TIPO_DOCUMENTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_DOCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_DOCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_DOC {
            get {
                return this.DES_DOCField;
            }
            set {
                if ((object.ReferenceEquals(this.DES_DOCField, value) != true)) {
                    this.DES_DOCField = value;
                    this.RaisePropertyChanged("DES_DOC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_DOC {
            get {
                return this.ID_DOCField;
            }
            set {
                if ((this.ID_DOCField.Equals(value) != true)) {
                    this.ID_DOCField = value;
                    this.RaisePropertyChanged("ID_DOC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_DISTRITO", Namespace="http://schemas.datacontract.org/2004/07/WcfServicio")]
    [System.SerializableAttribute()]
    public partial class TB_DISTRITO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_DISTRITOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOM_DISTRITOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_DISTRITO {
            get {
                return this.ID_DISTRITOField;
            }
            set {
                if ((this.ID_DISTRITOField.Equals(value) != true)) {
                    this.ID_DISTRITOField = value;
                    this.RaisePropertyChanged("ID_DISTRITO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOM_DISTRITO {
            get {
                return this.NOM_DISTRITOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOM_DISTRITOField, value) != true)) {
                    this.NOM_DISTRITOField = value;
                    this.RaisePropertyChanged("NOM_DISTRITO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaNegocio.IServicioNegocio")]
    public interface IServicioNegocio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocio/RegistrarUsuario", ReplyAction="http://tempuri.org/IServicioNegocio/RegistrarUsuarioResponse")]
        string RegistrarUsuario(ProyectoIntegrador.ReferenciaNegocio.TB_USUARIO reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocio/RegistrarUsuario", ReplyAction="http://tempuri.org/IServicioNegocio/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<string> RegistrarUsuarioAsync(ProyectoIntegrador.ReferenciaNegocio.TB_USUARIO reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocio/EnviarCorreoConfimacion", ReplyAction="http://tempuri.org/IServicioNegocio/EnviarCorreoConfimacionResponse")]
        string EnviarCorreoConfimacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocio/EnviarCorreoConfimacion", ReplyAction="http://tempuri.org/IServicioNegocio/EnviarCorreoConfimacionResponse")]
        System.Threading.Tasks.Task<string> EnviarCorreoConfimacionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocio/ListarTipoUsuario", ReplyAction="http://tempuri.org/IServicioNegocio/ListarTipoUsuarioResponse")]
        ProyectoIntegrador.ReferenciaNegocio.TB_TIPO_USUARIO[] ListarTipoUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocio/ListarTipoUsuario", ReplyAction="http://tempuri.org/IServicioNegocio/ListarTipoUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoIntegrador.ReferenciaNegocio.TB_TIPO_USUARIO[]> ListarTipoUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocio/ListarTipoDocumento", ReplyAction="http://tempuri.org/IServicioNegocio/ListarTipoDocumentoResponse")]
        ProyectoIntegrador.ReferenciaNegocio.TB_TIPO_DOCUMENTO[] ListarTipoDocumento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocio/ListarTipoDocumento", ReplyAction="http://tempuri.org/IServicioNegocio/ListarTipoDocumentoResponse")]
        System.Threading.Tasks.Task<ProyectoIntegrador.ReferenciaNegocio.TB_TIPO_DOCUMENTO[]> ListarTipoDocumentoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocio/ListarDistritos", ReplyAction="http://tempuri.org/IServicioNegocio/ListarDistritosResponse")]
        ProyectoIntegrador.ReferenciaNegocio.TB_DISTRITO[] ListarDistritos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioNegocio/ListarDistritos", ReplyAction="http://tempuri.org/IServicioNegocio/ListarDistritosResponse")]
        System.Threading.Tasks.Task<ProyectoIntegrador.ReferenciaNegocio.TB_DISTRITO[]> ListarDistritosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioNegocioChannel : ProyectoIntegrador.ReferenciaNegocio.IServicioNegocio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioNegocioClient : System.ServiceModel.ClientBase<ProyectoIntegrador.ReferenciaNegocio.IServicioNegocio>, ProyectoIntegrador.ReferenciaNegocio.IServicioNegocio {
        
        public ServicioNegocioClient() {
        }
        
        public ServicioNegocioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioNegocioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioNegocioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioNegocioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RegistrarUsuario(ProyectoIntegrador.ReferenciaNegocio.TB_USUARIO reg) {
            return base.Channel.RegistrarUsuario(reg);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarUsuarioAsync(ProyectoIntegrador.ReferenciaNegocio.TB_USUARIO reg) {
            return base.Channel.RegistrarUsuarioAsync(reg);
        }
        
        public string EnviarCorreoConfimacion() {
            return base.Channel.EnviarCorreoConfimacion();
        }
        
        public System.Threading.Tasks.Task<string> EnviarCorreoConfimacionAsync() {
            return base.Channel.EnviarCorreoConfimacionAsync();
        }
        
        public ProyectoIntegrador.ReferenciaNegocio.TB_TIPO_USUARIO[] ListarTipoUsuario() {
            return base.Channel.ListarTipoUsuario();
        }
        
        public System.Threading.Tasks.Task<ProyectoIntegrador.ReferenciaNegocio.TB_TIPO_USUARIO[]> ListarTipoUsuarioAsync() {
            return base.Channel.ListarTipoUsuarioAsync();
        }
        
        public ProyectoIntegrador.ReferenciaNegocio.TB_TIPO_DOCUMENTO[] ListarTipoDocumento() {
            return base.Channel.ListarTipoDocumento();
        }
        
        public System.Threading.Tasks.Task<ProyectoIntegrador.ReferenciaNegocio.TB_TIPO_DOCUMENTO[]> ListarTipoDocumentoAsync() {
            return base.Channel.ListarTipoDocumentoAsync();
        }
        
        public ProyectoIntegrador.ReferenciaNegocio.TB_DISTRITO[] ListarDistritos() {
            return base.Channel.ListarDistritos();
        }
        
        public System.Threading.Tasks.Task<ProyectoIntegrador.ReferenciaNegocio.TB_DISTRITO[]> ListarDistritosAsync() {
            return base.Channel.ListarDistritosAsync();
        }
    }
}
